import React from "react";
import { useNavigate } from "react-router-dom";

function About() {
    const navigate = useNavigate();
    return (
        <div>
            <h2>About</h2>
            <div>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut porttitor porttitor metus nec tristique. Integer imperdiet ullamcorper porttitor. Fusce consequat, odio ut tempor tincidunt, ligula leo vestibulum orci, vitae sollicitudin dolor nulla vitae tellus. Nam placerat, ex vel dignissim gravida, quam eros imperdiet mauris, non tempor lacus urna non eros. Donec pretium, mauris a egestas congue, lorem orci malesuada nunc, sit amet posuere tortor orci eu sem. Nam tellus quam, lacinia sit amet sapien vel, rhoncus elementum mi. Praesent nec sodales metus, eu rhoncus magna. Donec aliquet purus sed congue ultricies. Phasellus vel posuere ex, eu venenatis justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla ultrices tortor ac ex bibendum sollicitudin. Maecenas lacinia euismod luctus. Etiam mattis lectus sit amet convallis scelerisque. Praesent sed tristique mauris. Fusce blandit, lectus sit amet semper consectetur, dui ligula dictum nunc, et tempor nisi dolor non lectus.

                Curabitur rutrum vitae diam quis vulputate. Vivamus sed congue diam, eu porta mi. Nam molestie pretium dui in condimentum. Etiam rutrum nunc et nisl dapibus commodo. Curabitur nec auctor felis. Maecenas sed felis varius, pharetra nunc eget, fringilla ipsum. Vestibulum eleifend ex urna, vel consequat lorem fermentum eget. Sed gravida blandit massa, vel porttitor libero congue at. Praesent eleifend tempor sem nec faucibus. Nunc vel tortor lacinia odio sodales lobortis quis sollicitudin dui. Integer ipsum lectus, consectetur id ligula ut, blandit rutrum lorem. Fusce ex sapien, ullamcorper tempor urna non, efficitur placerat nulla. Cras rhoncus nunc blandit enim porta, ac bibendum orci convallis.

                Mauris euismod consectetur sapien, tincidunt finibus dolor rhoncus sed. Nulla malesuada tristique sapien, aliquam ullamcorper augue. In dignissim felis vulputate velit vehicula suscipit. Vestibulum libero risus, volutpat ac eros quis, vestibulum luctus dui. Praesent egestas sem sed maximus aliquam. Aliquam molestie mauris vel tincidunt tincidunt. Proin risus purus, porta quis gravida ut, iaculis nec nibh. Quisque lectus turpis, feugiat et risus at, volutpat rhoncus quam. Donec at arcu tempor, scelerisque orci vel, vehicula lectus. Nulla ac dolor ultricies, feugiat risus sit amet, vestibulum erat. Nam ut libero eu quam ornare congue. Proin tristique orci at nibh eleifend dignissim. Aliquam at imperdiet nisi.

                Etiam non fringilla eros. Aenean turpis dui, blandit eget consectetur ac, suscipit nec purus. Sed a sollicitudin lorem, nec placerat orci. Nam sed lacus dui. Donec et augue urna. In efficitur auctor lectus, at rutrum enim tincidunt malesuada. Curabitur lorem urna, porta sed lorem ac, dictum hendrerit orci. Etiam convallis venenatis elit, eu fermentum mauris faucibus nec. Morbi et scelerisque quam.

                Praesent eu egestas tortor. Aliquam aliquet magna eget neque rhoncus, placerat consectetur metus tincidunt. Donec tortor ipsum, varius sit amet nisl id, vulputate semper lorem. Praesent sit amet neque vel augue placerat ullamcorper sed bibendum augue. In hac habitasse platea dictumst. Integer a lectus sit amet metus pharetra posuere quis quis enim. Morbi vitae mi commodo, gravida eros vitae, euismod ante. Vivamus nisi ante, efficitur id tempus sed, dignissim ut ligula. Sed finibus fermentum condimentum. Mauris sagittis lobortis nunc at fringilla. Aliquam vehicula ultricies velit id ullamcorper. Curabitur eget mattis nunc. Morbi nisl ex, lacinia sed ante non, suscipit vestibulum turpis. Curabitur tincidunt rhoncus lectus non lacinia. Nunc hendrerit, libero non semper facilisis, odio felis facilisis magna, non semper erat est sit amet sapien. Donec efficitur vestibulum sem id iaculis.

                Sed facilisis nec odio congue varius. Nunc lacus sapien, ultricies sit amet nunc et, consectetur ullamcorper magna. Cras vehicula elit tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse finibus, lacus non sodales consequat, nisl nulla malesuada lorem, vulputate facilisis ex dui at purus. Aenean eu nunc ac ipsum varius ultrices nec at nibh. Proin mi mi, commodo et ultricies at, lobortis vel orci. Donec nulla metus, dignissim a imperdiet ornare, faucibus et lacus. Nullam placerat venenatis nibh id volutpat. Cras sagittis imperdiet dignissim. In egestas felis vel neque pharetra placerat. Donec vitae erat ex.

                Maecenas convallis porta elit eu placerat. Phasellus nec dignissim risus, ac eleifend orci. Maecenas elementum nulla sem, vel cursus urna cursus et. Etiam at ligula nunc. Aenean dictum, arcu ac condimentum elementum, tortor felis sodales purus, vitae ultrices leo est sit amet nulla. Phasellus aliquet sollicitudin elit, a sagittis quam pellentesque vitae. Duis maximus, nibh non aliquet dapibus, metus orci semper metus, sed accumsan lectus eros eget turpis. Nulla at urna ante. Duis sagittis, neque at fringilla volutpat, est orci lacinia turpis, in pretium metus tellus a libero. Morbi vel bibendum metus. Praesent suscipit non quam scelerisque placerat. Nullam leo tellus, accumsan id condimentum nec, ornare non nibh. Nam vehicula hendrerit sem, ut ultrices ante tincidunt eu. Etiam facilisis tellus eget elit ultrices, a commodo mauris posuere. Nam a pellentesque nisl. Ut commodo, purus nec sagittis feugiat, urna odio ornare erat, vitae mattis mauris magna ut magna.

                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse interdum nisl id pellentesque sodales. Etiam tortor eros, lacinia eu dolor in, sollicitudin condimentum velit. Praesent laoreet hendrerit augue, a iaculis velit finibus et. Phasellus in nisi at ante mattis gravida. Duis finibus odio hendrerit arcu ultricies, eu accumsan ex lacinia. Curabitur id orci at purus varius consequat tempor sagittis nibh. Suspendisse bibendum mi quis turpis malesuada tempus. Maecenas at fringilla diam. Phasellus orci magna, mattis ut egestas nec, ornare quis augue. Donec finibus vitae libero nec accumsan.

                Nam vitae tempus dolor. Morbi fermentum nulla risus, quis convallis lacus eleifend eget. Suspendisse eleifend purus ac sapien porttitor, id sollicitudin quam placerat. Aliquam erat volutpat. Maecenas vel urna vel ex accumsan lacinia ac non augue. Maecenas pharetra nisl ac turpis tempor, at placerat mauris dignissim. Vivamus dolor felis, vestibulum quis porttitor vitae, feugiat sit amet enim. Suspendisse auctor velit lorem. Vestibulum et auctor est, at egestas sem.

                Aliquam dictum nibh in tristique vulputate. Mauris quis nisi vitae ligula accumsan euismod. Nunc at consectetur lacus. Donec quis dapibus magna. Vestibulum venenatis orci vel sodales maximus. Quisque turpis diam, sodales in magna vel, gravida sollicitudin odio. Fusce fringilla sodales imperdiet. Sed vel lectus lobortis, dapibus urna ut, egestas ligula. Donec id elit urna. Nulla at efficitur enim, ut consectetur sapien. Morbi ut ipsum ut leo faucibus dapibus. Donec consectetur urna ut eleifend efficitur. Morbi vel euismod tortor. In at auctor ante. Proin tristique lacus sed iaculis lobortis.

                Nulla euismod, ligula non efficitur consectetur, enim ex dictum est, id vehicula odio quam vel nisi. Nam ultricies lacus a tellus lobortis congue. Praesent sed volutpat magna, at hendrerit leo. Aenean tincidunt leo eget erat sagittis, et feugiat neque congue. Aliquam ac auctor eros. Proin lacus purus, posuere et finibus ac, interdum sit amet nibh. Sed feugiat ornare nunc in semper. Cras nec dolor porttitor, ornare ligula id, faucibus lorem. Aenean rhoncus dolor quis arcu sollicitudin, quis aliquet mauris elementum. Etiam malesuada dui diam, vitae feugiat est porttitor nec. Sed dictum, ante in placerat venenatis, elit diam accumsan nibh, vestibulum dignissim orci leo et augue. Phasellus eget tempor ante. In ac ante bibendum arcu iaculis imperdiet eget eu eros. Donec vitae velit quis sapien tempor imperdiet.

                Ut vel tincidunt risus. Duis et tincidunt sem, ut iaculis lacus. Suspendisse potenti. Nunc maximus orci fermentum augue sodales, sed laoreet neque imperdiet. Fusce et nibh ex. Vivamus tempor, massa id hendrerit bibendum, ipsum orci tincidunt orci, vel aliquet diam nunc et lacus. Curabitur facilisis nec sem ut tempor. In dignissim nibh ipsum, a ultricies orci efficitur nec. Cras ullamcorper quis metus vel porttitor. Nulla posuere posuere urna, quis laoreet est cursus nec. Vestibulum bibendum vel sem et mattis. Curabitur porttitor elit ligula, nec congue sem condimentum ac.

                Vestibulum porta, odio a pharetra feugiat, nunc urna dapibus neque, id lacinia felis nulla eu elit. In id ex metus. Vivamus tempor scelerisque felis eget accumsan. In lacinia, leo nec auctor finibus, mi tortor rutrum libero, in dictum ex diam nec neque. Suspendisse sodales sem sit amet mauris commodo, vel pretium dui dictum. Curabitur vestibulum lectus leo, id finibus mauris porta ut. Nullam tincidunt odio tortor, non fringilla ligula rutrum nec.

                In hac habitasse platea dictumst. Praesent eu elit at magna hendrerit ultrices ac blandit eros. Donec maximus odio in libero congue, vitae ornare mi ultricies. Ut vestibulum iaculis purus, vel pellentesque eros sodales ac. Duis ac ipsum id libero laoreet laoreet. Donec pulvinar eu ex vitae porta. Maecenas nec eros sem. Donec ut volutpat quam, non imperdiet ex.

                Aliquam ornare, ipsum ut mollis laoreet, eros nisl vehicula lectus, eu dictum odio eros congue ipsum. Quisque ut semper magna, id vestibulum nisl. Pellentesque finibus et nisl eu efficitur. Cras venenatis laoreet augue, ac egestas tellus tincidunt eu. Fusce arcu ligula, lacinia nec dolor eu, tincidunt hendrerit velit. Cras arcu libero, aliquet non finibus sed, tincidunt ultricies orci. In dapibus elit sit amet libero tempor hendrerit. Donec molestie risus commodo lobortis iaculis. Quisque at lectus mollis, scelerisque libero a, bibendum metus.

                Vivamus malesuada, erat at lacinia cursus, sapien nunc auctor ex, eu pellentesque ex nibh eget eros. Sed venenatis egestas odio, in semper ex tempus pulvinar. Donec tincidunt cursus ex. Ut vel dolor vel ipsum volutpat cursus. Curabitur tincidunt nisi nec placerat efficitur. In sit amet velit ac mi mattis rhoncus sit amet sed augue. Curabitur iaculis nunc lacinia dolor convallis, eu fermentum elit pulvinar. Maecenas sed placerat ante.

                Maecenas vulputate leo non libero vulputate feugiat. Integer a laoreet quam, id fermentum sem. Vivamus interdum vulputate sem eget tincidunt. Aliquam erat volutpat. Praesent porta imperdiet turpis vitae pretium. Sed sagittis dignissim lectus sit amet venenatis. Morbi sit amet mollis augue, ultrices porttitor justo. Nunc fringilla elit at pellentesque posuere. Duis laoreet pretium rhoncus. Duis nulla ante, viverra convallis risus ut, molestie gravida leo. Morbi et metus sed ligula sagittis placerat. Aliquam molestie metus eu vestibulum accumsan. Nam vitae placerat turpis. Integer quis mattis ante. Ut accumsan pharetra dui.

                Suspendisse a ante condimentum, sollicitudin risus vehicula, fringilla nunc. Donec lorem eros, vestibulum vitae ligula eget, dapibus malesuada enim. Integer urna diam, porttitor hendrerit nisi at, gravida fermentum leo. Phasellus sit amet tempor arcu. Duis vel faucibus magna, eget porta mauris. Maecenas varius mauris metus, non placerat dolor tincidunt sit amet. Aenean eget dui iaculis, facilisis ligula tempus, efficitur felis. Donec eu turpis viverra, sollicitudin sapien eget, dictum elit. Aenean ut tincidunt sapien, a iaculis lacus. Duis blandit eleifend dolor sit amet egestas. Sed sed efficitur nulla, sit amet sodales eros. Aliquam mattis ipsum vel augue volutpat suscipit. Curabitur condimentum arcu in eleifend condimentum. Nam blandit velit mi, non sollicitudin arcu vulputate quis.

                Donec sagittis accumsan cursus. Maecenas eu auctor nibh. Nullam nulla lacus, vulputate vel tellus eget, pharetra laoreet nunc. Praesent euismod ut velit a pellentesque. Vivamus a nisi in lacus finibus cursus. Vivamus pharetra mauris arcu, ut luctus felis volutpat in. Mauris lobortis eget ante ornare dapibus. Aliquam tincidunt leo sapien, a convallis dui molestie sit amet. Proin ultrices, massa sit amet molestie scelerisque, ante tortor mattis ipsum, ac tincidunt ipsum tortor nec dui. Nunc sed justo quam. Sed viverra bibendum elit, ac lobortis augue commodo sed.

                Proin enim ipsum, semper vitae auctor sit amet, scelerisque sit amet diam. Sed accumsan enim at vehicula consectetur. Donec accumsan, ipsum non vehicula fermentum, risus sapien vehicula felis, vel sollicitudin nisl lectus sed elit. Phasellus mattis erat faucibus nulla tincidunt, ut semper ipsum rhoncus. Nunc hendrerit fermentum lacus, nec dictum mi scelerisque ut. Pellentesque feugiat elementum libero, id condimentum dui ornare in. Mauris nec erat sed odio suscipit imperdiet tristique ut turpis. Donec vel lacinia tellus.
            </div>

            <div style={{margin : "2rem"}}><button style={{padding: "1rem", fontSize : "1.2rem"}} onClick={() => navigate(-1)}>Go back</button></div>
        </div>
    )
}

export default About;